from datetime import datetime
from app import db


class User(db.Model):
    id = db.Column(db.String(64), primary_key=True)
    username = db.Column(db.String(150), unique=True, nullable=False)
    email = db.Column(db.String(200), unique=True, nullable=False)
    password_hash = db.Column(db.String(300), nullable=False)
    role = db.Column(db.String(50), nullable=False)
    full_name = db.Column(db.String(200))
    phone = db.Column(db.String(100))
    address = db.Column(db.String(300))
    court_name = db.Column(db.String(200))
    jurisdiction = db.Column(db.String(200))
    bar_number = db.Column(db.String(100))
    specialization = db.Column(db.String(200))
    law_firm = db.Column(db.String(200))
    case_number = db.Column(db.String(200))
    id_number = db.Column(db.String(200))
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

class Case(db.Model):
    id = db.Column(db.String(64), primary_key=True)
    case_number = db.Column(db.String(200))
    case_title = db.Column(db.String(300))
    case_type = db.Column(db.String(200))
    plaintiff = db.Column(db.String(300))
    defendant = db.Column(db.String(300))
    lawyer_id = db.Column(db.String(64), db.ForeignKey('user.id'))
    client_id = db.Column(db.String(64), db.ForeignKey('user.id'))
    status = db.Column(db.String(100))
    filing_date = db.Column(db.String(100))
    description = db.Column(db.Text)
    created_by = db.Column(db.String(64))
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

class Hearing(db.Model):
    id = db.Column(db.String(64), primary_key=True)
    case_id = db.Column(db.String(64), db.ForeignKey('case.id'))
    case_title = db.Column(db.String(300))
    hearing_date = db.Column(db.String(100))
    hearing_time = db.Column(db.String(100))
    courtroom = db.Column(db.String(200))
    judge_name = db.Column(db.String(200))
    hearing_type = db.Column(db.String(200))
    notes = db.Column(db.Text)
    created_by = db.Column(db.String(64))
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    status = db.Column(db.String(100))

class File(db.Model):
    id = db.Column(db.String(64), primary_key=True)
    original_filename = db.Column(db.String(300))
    encrypted_filename = db.Column(db.String(500))
    uploader_id = db.Column(db.String(64), db.ForeignKey('user.id'))
    uploader_name = db.Column(db.String(200))
    uploader_role = db.Column(db.String(50))
    recipient_id = db.Column(db.String(64))
    case_id = db.Column(db.String(64))
    description = db.Column(db.Text)
    file_size = db.Column(db.Integer)
    is_encrypted = db.Column(db.Boolean, default=False)
    encryption_key_a = db.Column(db.Integer)
    encryption_key_b = db.Column(db.Integer)
    uploaded_at = db.Column(db.DateTime, default=datetime.utcnow)

class Message(db.Model):
    id = db.Column(db.String(64), primary_key=True)
    sender_id = db.Column(db.String(64))
    sender_name = db.Column(db.String(200))
    sender_role = db.Column(db.String(50))
    recipient_id = db.Column(db.String(64))
    recipient_role = db.Column(db.String(50))
    subject = db.Column(db.String(300))
    message = db.Column(db.Text)
    is_encrypted = db.Column(db.Boolean, default=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    read = db.Column(db.Boolean, default=False)

class Appointment(db.Model):
    id = db.Column(db.String(64), primary_key=True)
    lawyer_id = db.Column(db.String(64))
    lawyer_name = db.Column(db.String(200))
    client_id = db.Column(db.String(64))
    case_id = db.Column(db.String(64))
    appointment_date = db.Column(db.String(100))
    appointment_time = db.Column(db.String(100))
    appointment_type = db.Column(db.String(200))
    location = db.Column(db.String(300))
    notes = db.Column(db.Text)
    status = db.Column(db.String(100))
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
